CREATE TABLE books (
 id SERIAL PRIMARY KEY,
 title VARCHAR(255) NOT NULL,
 isbn VARCHAR(20) NOT NULL,
 price DECIMAL(10,2) NOT NULL
);

CREATE TABLE authors (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    age INT NOT NULL
);
